public class programa{
    private Integer memoriaRamlocada;
    private Integer SSDOcupado;
    private Integer Nucleos;
    public Integer quantidadedeOperacoes;

    public Integer getMemoriaramlocada(){
        return this.memoriaRamlocada;
    }

    public Integer setMemoriaramlocada(){
        this.memoriaRamlocada = memoriaRamlocada ;
    
    }

    public Integer getSSDOcupado(){
        return this.SSDOcupado;
    }

    public Integer getNucleos1(){
        return this.Nucleos;
    }
}